#!/usr/bin/env/bash
# using sed  command to perform redirection in web page

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /vaar/www/html/index.html

string_for_repl="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/habtew permanent;"

sudo sed -i "s/server_name _;/$string_for_repl/" /etc/nginx/sites-enabled/default
sudo service nginx restart
